In [1]:
import numpy as np

In [3]:
#cria uma matriz unidimencional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [4]:
#cria o array com um tipo especifico 
# cria o array como float de 64 bits
mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [5]:
#mudar o tipo do array
#podemos tranformar tipos de dados de arrays
mtnew = np.array([1.4,1.5,-5.6,9.42,4.999999])
print(mtnew)
#quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4       1.5      -5.6       9.42      4.999999]
[ 1  1 -5  9  4]


In [6]:
#pode=se fazer o inverso da corvenção
mt5 = np.array([1,2,3,4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [8]:
#mais de uma dimenção
# Cria uma matriz bidimencional
mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [10]:
#criar array vazios tipificados
#empty significa que não são inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)
print("________________")
#cria uma matriz 4x3 com valores zerados
zeros = np.zeros([4,3])
print(zeros)
print("___________________")
#cria com valores iguais
um = np.ones([5,7])
print(um)
print("__________________")
#Cria matriz quadrad com diagonal principal com valores 1 e os ooutros valores como zero
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
________________
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
___________________
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
__________________
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
#valores aleatórios entre zero e um 
ale = np.random.random((5))
print(ale)
#valors aleatorios distr, normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
#valores aleatórios 3 x 4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.34378106 0.24803735 0.72624433 0.06672903 0.45336607]
[1.84224617 1.27119938 0.59363825 0.77661521 1.53881009]
[[8.02026248 3.88420034 9.28456711 4.16953722]
 [4.79391927 4.30326588 5.70845583 0.24154201]
 [3.5718954  4.42884846 6.80678346 4.2889151 ]]


In [14]:
#outra forma de gerar numeros aleatorios
#uso de semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)

#gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [17]:
#unique remove repetições
j = np.array([11,12,14,15,16,17,12,13,11,18,19,20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [18]:
#funções especificas do Numpy
# Cria matriz bidimencional K
k = np.array([[17,22,43],[24,25,14],[15,24,32]])
#mostra amatriz k
print(k)
#mnostra um elemento especifico da matriz k
print(k[0][1])
#mostra o tamanho das dimenções da matriz k
print(k.shape)


[[17 22 43]
 [24 25 14]
 [15 24 32]]
22
(3, 3)


In [19]:
#funções matematicas
#mostra o maior valor da mtriz k
print(k.max())
#mostra o menor valor da matriz k
print(k.min())
#mostra a soma dos valores da matriz 
print(k.sum())
#mostra a media da matriz k
print(k.mean())
#mostra o valor do desvio padrão d
print(k.std())

43
14
216
24.0
8.563488385776752


In [24]:
#funções universais aplicada a todos os elementos
# mostra o valor da reaiz quadrado de todos os elementos
k1 = np.array([1,4,9,16])
print(np.sqrt(k1))
#mostra o valor explonencial
print(np.exp(k1))

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [32]:
#extração de elementos
m = np.array([1,2,3,4,5,6])
# mostra o elemento da posi~ção 2
print(m[1])
# mostra o array criado a partoir da posição 0, dos elementos
print(m[0:2])
#mostra o array criado a partir da segunda posição
print(m[1:])
#mostra o array criado a partir do anetepenultima
print(m[-3:])


2
[1 2]
[2 3 4 5 6]
[4 5 6]


In [34]:
#extração de linhas e colunas
l = np.array([[4,5],[6,1],[7,4]])
print(l)
print("----------------")
#Primeira linha e todas as colunas
l_linha_1 = l[0, : ]
print(l_linha_1)
print("----------------")
#Segunda linha
l_linha_2 = l[1, :]
print(l_linha_2)
print("----------------")
#terceira linha
l_linha_2 = l[2, :]
print(l_linha_2)
print("----------------")
#todas as linhas e a terceira coluna
l_linha_3 = l[:, 0]
print(l_linha_3)
print("----------------")
#todas as linhas e a segunda colhna
l_linha_4 = l[:, 1]
print(l_linha_4)
print("----------------")


[[4 5]
 [6 1]
 [7 4]]
----------------
[4 5]
----------------
[6 1]
----------------
[7 4]
----------------
[4 6 7]
----------------
[5 1 4]
----------------
